### ISSUE TITLE
New Livery

### ISSUE THREAD

**Issue by hamzaelasmar** [Stratosphere-Studios/Stratosphere-Liveries#13]
I saw an egyptair 777 and i would like to recreate it. I was just requesting for approval to make this livery and get it uploaded in this github repo. I will make it myself.

**Comment by remenkemi** [comment]
No need for approval, go ahead!

**Comment by hamzaelasmar** [comment]
Thanks im inspecting the files and knowing what they do. Should be done by tomorrow or the day after
