### ISSUE TITLE
how to download

### ISSUE THREAD

**Issue by DaCoolBoi15** [Stratosphere-Studios/Stratosphere-Liveries#21]

**Comment by Ker1010** [comment]
https://github.com/Stratosphere-Studios/Stratosphere-Liveries
![image](https://github.com/Stratosphere-Studios/Stratosphere-Liveries/assets/42411469/1e7a2b6f-7fc5-49a8-9804-b029742c4c37)
1. Unzip it
2. Find the livery you want to use
3. Put it to your aircraft livery folder

btw is currently not possible to download single livery
