### ISSUE TITLE
Southwind Livery Font and Potition

### ISSUE THREAD

**Issue by remenkemi** [Stratosphere-Studios/Stratosphere-Liveries#28]
@yelloyelloman i have a suggestion for your Southwind livery, it looks like the font is slightly off and is positioned too high. Or maybe it's just stretched vertically.
![image](https://github.com/Stratosphere-Studios/Stratosphere-Liveries/assets/64425497/62f1faf9-23a8-4ff4-821a-73b3e53aae15)
![image](https://github.com/Stratosphere-Studios/Stratosphere-Liveries/assets/64425497/57d0b8f3-b271-4d41-b115-97eef40433d1)
Notice how the windows go almost straight through the S in the photo but just the bottom part in our livery. Also notice how the real letters are shorter and rounder. especially compare the h and d

**Comment by yelloyelloman** [comment]
i will soon fix this livery as i need to do Etihad Airways (A6-ETG) first.

**Comment by yelloyelloman** [comment]
the Southwind Airlines fix is now done, neither the Etihad livery. will make a pull request later as i will make 5Y-KZY

**Comment by yelloyelloman** [comment]
please close this issue if possible as this was already done

**Comment by remenkemi** [comment]
> please close this issue if possible as this was already done

Just saw this lol, closing
