### ISSUE TITLE
It's better to have a tail.psd file for paint kit

### ISSUE THREAD

**Issue by A350winglets** [Stratosphere-Studios/Stratosphere-Liveries#8]
It's strange that all paint kit files are .psd but only tail is a .xcf file so I made a .psd for it.
here is the file: https://drive.google.com/file/d/1Wxf1tH8zSdhLIoedIIXWP3KBRC64CPqV/view?usp=sharing

**Comment by remenkemi** [comment]
Thanks! I'll put it on the master.
